import type { BrowserContext, Page } from '@playwright/test';
import { test as base } from './base';
import { PageManager } from '../pages/page-manager';
import { env } from '../support/env';
import { validUser } from '../support/data/users';
import { Selectors } from '../support/data/selectors';
import { guestAuthFile } from '../support/auth-files';

type User = ReturnType<typeof validUser>;

type AuthFixtures = {
    // Host (default worker identity)
    pages: PageManager;
    hostPage: Page;
    hostPages: PageManager;

    // Guest (second context, isolated storage state)
    guestContext: BrowserContext;
    guestPage: Page;
    guestPages: PageManager;

    // Flow fixtures (operate on the default `page` = host)
    authenticated: void;
    registered: User;
    loggedOut: void;
};

// TODO the following fixtures do need to be cleaned up, as most of them are redundant shit generated by AI
export const test = base.extend<AuthFixtures>({
    pages: async ({ page }, use) => {
        await use(new PageManager(page));
    },

    hostPage: async ({ page }, use) => {
        await use(page);
    },

    hostPages: async ({ pages }, use) => {
        await use(pages);
    },

    guestContext: async ({ browser }, use) => {
        const context = await browser.newContext({ storageState: guestAuthFile });
        await use(context);
        await context.close();
    },

    guestPage: async ({ guestContext }, use) => {
        await use(await guestContext.newPage());
    },

    guestPages: async ({ guestPage }, use) => {
        await use(new PageManager(guestPage));
    },

    authenticated: async ({ page }, use) => {
        await page.goto(env.BASE_URL);
        await page.waitForSelector(Selectors.navbarUserBtn);
        await use();
    },

    registered: async ({ pages, page }, use) => {
        const user = validUser();
        await pages.registerPage.goto();
        await pages.registerPage.register(user.firstName, user.lastName, user.email, user.password, user.password);
        await page.waitForURL(env.BASE_URL);
        await page.waitForSelector(Selectors.navbarUserBtn);
        await use(user);
    },

    loggedOut: async ({ pages, page }, use) => {
        await page.goto(env.BASE_URL);
        await page.waitForSelector(Selectors.navbarUserBtn);
        await pages.navbar.logout();
        await use();
    },
});
